dubbo:
  application:
    name: dubbo-provider
  registry:
    address: 172.18.231.8:32181
    #address: zk-sc:2181
    # 读者请自行更改zookeeper地址
    protocol: zookeeper
    check: false
  protocol:
    name: dubbo
    port: 30003
  monitor:
    protocol: register
  consumer:
    check: false
    timeout: 3000

server:
  port: 8061
spring:
  application:
    name: dubbo-provider
  zipkin:
    base-url: http://172.18.231.8:30086
  sleuth:
    sampler:
      probability: 1.0